import { existsSync } from "node:fs";
import { readFile, copyFile } from "node:fs/promises";
import { join } from "node:path";
import type {
  BibleManager,
  EpisodeSummaryRecord,
  NarrativeDelta,
} from "../bible/bible-manager.js";
import {
  HierarchicalFilmAssembler,
  type SceneAssemblyInput,
} from "../assembly/hierarchical-assembler.js";
import { extractNarrativeDeltaFromScript } from "./episodic-pipeline.js";
import { isFfmpegAvailable, runFfmpeg } from "../media/ffmpeg.js";
import { log } from "../utils/logger.js";

export interface FinalizeProductionOptions {
  seriesId: string;
  episodeNumber: number;
  script: any;
  bible: BibleManager;
  outputDir?: string;
  allowMockMedia?: boolean;
  onFinalize?: (ctx: {
    seriesId: string;
    episodeNumber: number;
    script: any;
    bible: BibleManager;
  }) => Promise<{ masterVideoPath?: string; canonCommitted?: boolean }>;
}

export interface FinalizeProductionResult {
  success: boolean;
  masterVideoPath?: string;
  canonCommitted?: boolean;
  commitId?: string;
  qaReport?: any;
  error?: string;
  missingApprovals?: string[];
  mockTakesDetected?: string[];
}

/**
 * Unified Finalize Service for Episodic Video Production (PR2).
 * Shared by Review Server (/api/series/finalize) and CLI (series finalize).
 *
 * Enforces:
 * 1. Completeness: every shot has an approved take whose file exists.
 * 2. Provenance Gate: reject any take generated by 'mock' provider (unless allowMockMedia is explicitly true).
 * 3. Audio Timeline Fidelity: reads timeline.json / audio.wav and supplies multi-track stems,
 *    preventing silent stems or missing soundtrack.
 * 4. QA Gate: validates manifest.qaReport.isValid === true before canon mutation.
 * 5. Lifecycle & Idempotency: requires approved lifecycle, computes deterministic commitId,
 *    and prevents duplicate commits on re-finalization.
 */
export async function finalizeEpisodeProduction(
  options: FinalizeProductionOptions
): Promise<FinalizeProductionResult> {
  const { seriesId, episodeNumber, script, bible } = options;

  if (!script.scenes || script.scenes.length === 0) {
    return {
      success: false,
      error: "Không thể finalize: Kịch bản không có cảnh nào (scenes rỗng).",
      missingApprovals: [],
    };
  }

  // 1. Completeness & Provenance check across all shots
  const approvedTakesMap = new Map<string, any>();
  const unapprovedShots: string[] = [];
  const mockTakesDetected: string[] = [];

  for (const scene of script.scenes) {
    for (const shot of scene.shots || []) {
      const approved = bible.getApprovedTakeForShot(
        seriesId,
        episodeNumber,
        shot.shotId
      );
      approvedTakesMap.set(shot.shotId, approved);

      if (!approved) {
        unapprovedShots.push(`${shot.shotId} (chưa có take được duyệt)`);
      } else if (!approved.local_path || !existsSync(approved.local_path)) {
        unapprovedShots.push(
          `${shot.shotId} (file take không tồn tại trên đĩa: ${approved.local_path || "rỗng"})`
        );
      } else if (!options.allowMockMedia && approved.provider === "mock") {
        mockTakesDetected.push(`${shot.shotId} (provider: mock)`);
      }
    }
  }

  if (unapprovedShots.length > 0) {
    return {
      success: false,
      error: `Không thể finalize: Còn ${unapprovedShots.length} shot chưa có take được duyệt (${unapprovedShots.join(", ")}).`,
      missingApprovals: unapprovedShots,
    };
  }

  if (mockTakesDetected.length > 0) {
    return {
      success: false,
      error: `[PROVENANCE GATE] Không thể commit canon với media mock. Các shot dùng mock: ${mockTakesDetected.join(", ")}. Vui lòng tạo media thật trước khi finalize.`,
      mockTakesDetected,
    };
  }

  // Custom onFinalize hook override if provided
  if (options.onFinalize) {
    const res = await options.onFinalize({
      seriesId,
      episodeNumber,
      script,
      bible,
    });
    return {
      success: true,
      masterVideoPath: res.masterVideoPath,
      canonCommitted: res.canonCommitted ?? true,
    };
  }

  // 2. Build assembly inputs
  const scenesInput: SceneAssemblyInput[] = (script.scenes || []).map(
    (sc: any, scIdx: number) => ({
      sceneNumber: sc.sceneNumber ?? scIdx + 1,
      sceneId: sc.sceneId || `scene_${scIdx + 1}`,
      shots: (sc.shots || []).map((sh: any) => {
        const approved = approvedTakesMap.get(sh.shotId);
        return {
          shotId: sh.shotId,
          sceneId: sc.sceneId || `scene_${scIdx + 1}`,
          takeId: approved?.id || `take_${sh.shotId}`,
          sourceClipPath: approved?.local_path || "",
          rawDurationSec: sh.durationSec,
          trimStartSec: 0,
          isApproved: Boolean(approved ? approved.is_approved : false),
        };
      }),
    })
  );

  const epNumStr = String(episodeNumber).padStart(2, "0");
  const baseEpDir = options.outputDir
    ? options.outputDir
    : join("output", "series", seriesId, `ep-${epNumStr}`);
  const assemblyOutputDir = join(baseEpDir, "assembly");

  // 3. Load Audio Cues and Timeline if available to prevent silent stem output
  let dialogueCues: any[] | undefined;
  let sfxCues: any[] | undefined;
  let ambienceCues: any[] | undefined;
  let bgmTrack: any | undefined;
  let subtitleCues: any[] | undefined;

  const timelinePath = join(baseEpDir, "timeline.json");
  if (existsSync(timelinePath)) {
    try {
      const rawTl = await readFile(timelinePath, "utf8");
      const tl = JSON.parse(rawTl);
      dialogueCues = tl.dialogueTrack;
      sfxCues = tl.sfxTracks;
      ambienceCues = tl.ambienceTrack;
      bgmTrack = tl.bgmTrack;
      subtitleCues = tl.subtitleCues;
    } catch (err: any) {
      log.warn(`[FINALIZE SERVICE] Không thể nạp timeline.json: ${err.message}`);
    }
  }

  const hierarchicalAssembler = new HierarchicalFilmAssembler({
    seriesId,
    episodeNumber,
    title: script.title,
    fps: script.fps || 30,
    aspectRatio: (script.aspectRatio || "9:16") as any,
    scenes: scenesInput,
    dialogueCues,
    sfxCues,
    ambienceCues,
    bgmTrack,
    subtitleCues,
    outputDir: assemblyOutputDir,
    requireApprovedShots: true,
  });

  const manifest = await hierarchicalAssembler.assemble();
  let masterPath = manifest.masterOutputs.masterVideoPath;

  if (!masterPath || !existsSync(masterPath)) {
    throw new Error(
      `[FINALIZATION GATE] Master video không tồn tại sau khi assemble: ${masterPath || "null"}`
    );
  }

  // 4. Ensure master video has combined audio if external audio.wav exists and master audio is silent
  const candidateAudio = join(baseEpDir, "audio.wav");
  if (existsSync(candidateAudio)) {
    try {
      if (await isFfmpegAvailable()) {
        const remuxedMaster = join(assemblyOutputDir, "master_with_audio.mp4");
        await runFfmpeg([
          "-y",
          "-i",
          masterPath,
          "-i",
          candidateAudio,
          "-map",
          "0:v:0",
          "-map",
          "1:a:0",
          "-c:v",
          "copy",
          "-c:a",
          "aac",
          "-b:a",
          "192k",
          remuxedMaster,
        ]);
        if (existsSync(remuxedMaster)) {
          masterPath = remuxedMaster;
        }
      }
    } catch (muxErr: any) {
      log.warn(`[FINALIZE SERVICE] Audio muxing warning: ${muxErr.message}`);
    }
  }

  // 5. QA Gate Verification
  if (!manifest.qaReport || manifest.qaReport.isValid === false) {
    const qaErrors = manifest.qaReport?.errors?.join("; ") || "QA report isValid is false";
    return {
      success: false,
      masterVideoPath: masterPath,
      qaReport: manifest.qaReport,
      error: `[FINALIZATION QA GATE] Master video không đạt tiêu chuẩn chất lượng: ${qaErrors}. Hủy bỏ commit canon.`,
    };
  }

  // 6. Multi-dimensional Narrative Delta Extraction & Deterministic Canon Commit
  const delta = extractNarrativeDeltaFromScript(script, bible, seriesId);

  const charactersAppeared = new Set<string>();
  for (const scene of script.scenes || []) {
    for (const char of scene.charactersPresent || []) {
      const charId = typeof char === "string" ? char : char?.characterId;
      if (charId) charactersAppeared.add(charId);
    }
  }

  const summaryRecord: EpisodeSummaryRecord = {
    series_id: seriesId,
    episode_number: episodeNumber,
    title: script.title,
    logline: script.logline,
    major_events: delta.major_events || [
      script.logline || `Hoàn thành tập ${episodeNumber}`,
    ],
    delta_changes: {
      master_video_path: masterPath,
      locations_visited:
        (delta.world_state_updates as any)?.locations_visited || [],
      characters_appeared: Array.from(charactersAppeared),
      wardrobe_changes: delta.character_wardrobe_updates || [],
      props_used: (delta.world_state_updates as any)?.props_active || [],
    },
    created_at: new Date().toISOString(),
  };

  // Transition lifecycle to approved by director prior to canon commit
  bible.setEpisodeLifecycle({
    seriesId,
    episodeNumber,
    status: "approved",
    reviewNotes: "director_approval",
    needsReview: false,
  });

  const commitResult = bible.commitEpisode(summaryRecord, delta, {
    seriesId,
    confirmationSource: "director_approval",
    force: false, // Enforce normal lifecycle validation
  });

  // Advance coverage ledger stage to "assembled" for all shots/scenes in this episode
  try {
    const episodeLedgers = bible.listCoverageLedgers(seriesId).filter(
      (l) => l.series_id === seriesId && l.episode_number === episodeNumber
    );
    for (const ledger of episodeLedgers) {
      if (ledger.adaptation_decision !== "omitted") {
        bible.upsertCoverageLedger({
          ...ledger,
          stage: "assembled",
        });
      }
    }
  } catch (covErr: any) {
    log.warn(`[FINALIZE SERVICE] Không thể cập nhật coverage stage sang assembled: ${covErr.message}`);
  }

  return {
    success: true,
    masterVideoPath: masterPath,
    canonCommitted: commitResult.applied,
    commitId: commitResult.commitId,
    qaReport: manifest.qaReport,
  };
}
